# Generated by Django 2.0.4 on 2018-05-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to='blog/article/'),
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='image',
            field=models.ImageField(blank=True, upload_to='blog/category/'),
        ),
    ]
